### ISSUE TITLE
Postgres error while bringing up a microservice

### ISSUE THREAD

**Issue by albamig** [Clariteia/minos_microservice_common#669]
The first time a microservice is launched, the following error shows up. Whenever you reboot it, the error disappears and everything works fine.

```python
2021-12-22 13:56:21 [T:MainThread] INFO:minos.common.setup: Building a 'PeriodicTaskScheduler' instance from config...
Traceback (most recent call last):
  File "/home/alberto/.pyenv/versions/3.9.5/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/alberto/.pyenv/versions/3.9.5/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/alberto/PycharmProjects/malebranche-server/src/__main__.py", line 6, in <module>
    main()
  File "/home/alberto/PycharmProjects/malebranche-server/src/cli.py", line 38, in main
    app()
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/alberto/PycharmProjects/malebranche-server/src/cli.py", line 28, in start
    launcher.launch()
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/minos/common/launchers.py", line 123, in launch
    self.loop.run_until_complete(self.setup())
  File "/home/alberto/.pyenv/versions/3.9.5/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/minos/common/setup.py", line 92, in setup
    await self._setup()
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/minos/common/launchers.py", line 177, in _setup
    await self.injector.wire(modules=self._external_modules + self._internal_modules)
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/minos/common/injectors.py", line 67, in wire
    await gather(*(injection.setup() for injection in self.injections.values()))
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/minos/common/setup.py", line 92, in setup
    await self._setup()
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/minos/aggregate/snapshots/pg/api.py", line 56, in _setup
    await self.writer.setup()
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/minos/common/setup.py", line 92, in setup
    await self._setup()
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/minos/aggregate/snapshots/pg/abc.py", line 24, in _setup
    await self.submit_query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/minos/common/database/abc.py", line 124, in submit_query
    await cursor.execute(operation=operation, parameters=parameters, timeout=timeout)
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/aiopg/connection.py", line 426, in execute
    await self._conn._poll(waiter, timeout)
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/aiopg/connection.py", line 881, in _poll
    await asyncio.wait_for(self._waiter, timeout)
  File "/home/alberto/.pyenv/versions/3.9.5/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/alberto/PycharmProjects/malebranche-server/.venv/lib/python3.9/site-packages/aiopg/connection.py", line 788, in _ready
    state = self._conn.poll()
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_extension_name_index"
DETAIL:  Key (extname)=(uuid-ossp) already exists.


Process finished with exit code 1
```

**Comment by garciparedes** [comment]
I'm proceeding to close this issue as it's already resolved by https://github.com/Clariteia/minos_microservice_aggregate/issues/37
